// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Core.BaseUtility;
using System;
using System.Collections.Generic;

namespace PSI.Domains.BWEntity
{
    public partial class BI_BP_AGENT_SNS 
    {
        public string? COMPANY { get; set; }
        public string? PSI_CONS_CODE { get; set; }
        public string? SALESOFFICE { get; set; }
        public string? REGION { get; set; }
        public string? DEPARTMENT { get; set; }
        public string? COUNTRY { get; set; }
       
        public string? MGGROUP { get; set; }
        public string? MG1 { get; set; }
        public string? MG2 { get; set; }
        public string? MG3 { get; set; }
        public string? MG4 { get; set; }
        public string? MG5 { get; set; }
        public string? PSI_ITEM_CODE { get; set; }
        public int? PSI_YYYYMM { get; set; }
        public string? SALES_TYPE { get; set; }
       
        public int? BP_QTY { get; set; }
        public decimal? BP_AMT { get; set; }

         public decimal? BP_COST_AMT { get; set; }

        public decimal? BP_GPAMT { get; set; }
        public DateTime? CREATEDON { get; set; }
        public DateTime? UPDATEDON { get; set; }

    }
}