// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace PSI.Domains.Models
{
    public partial class psidevdb01Context : DbContext
    {
        public psidevdb01Context()
        {
        }

        public psidevdb01Context(DbContextOptions<psidevdb01Context> options)
            : base(options)
        {
        }

        public virtual DbSet<Attachment> Attachments { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Attachment>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.DocumentName).HasMaxLength(100);

                entity.Property(e => e.DocumentPath).HasMaxLength(200);

                entity.Property(e => e.Extension).HasMaxLength(10);

                entity.Property(e => e.FileTypeName).HasMaxLength(100);

                entity.Property(e => e.UploadedBy).HasMaxLength(50);

                entity.Property(e => e.UploadedOn).HasColumnType("datetime");

                entity.Property(e => e.VirtualFileName).HasMaxLength(100);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}