// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Core.BaseUtility;
using System;
using System.Collections.Generic;

namespace PSI.Domains.Entity
{
    public partial class Attachment:BaseEntity
    {
        public int Id { get; set; }
        public string Extension { get; set; }
        public string DocumentName { get; set; }
        public bool? IsActive { get; set; }
        public string DocumentPath { get; set; }
        public string DocumentMonth { get; set; }
        public string VirtualFileName { get; set; }
        public string Base64String { get; set; }
        public int? FileTypeId { get; set; }
        public string FolderName { get; set; }
        public string FileTypeName { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string? UpdateBy { get; set; }

    }
}