// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Core.BaseUtility;


namespace PSI.Domains.Entity
{
    public partial class SP_DashMasterMonthly 
    {      
        public string MaterialCode { get; set; }
        public string CustomerName { get; set; }
        public string SalesCompany { get; set; }
        public string SupplierCode { get; set; }   
        public string TransPortMode { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }      
        public bool? IsActive { get; set; }        
        public string Months { get; set; }
        public string CustomerCode { get; set; }
        

    }
}