// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Core.BaseUtility;


namespace PSI.Domains.Entity
{
    public partial class SP_Get_CustomerWiseSaleQtyPrice : BaseEntity
    {      
        public int? SNSEntryId { get; set; }
        public int? SNSEntryQtyPriceId { get; set; }
        public int MonthYear { get; set; }
        public string? CustomerCode { get; set; }
        public string? MaterialCode { get; set; }
        public int? Quantity { get; set; }
        public decimal? Amount { get; set; }
        public string? AccountCode { get; set; }
    }
}