// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Core.BaseUtility;


namespace PSI.Domains.Entity
{
    public partial class SP_InsertSalesEntries : BaseEntity
    {      
        public int RowNo { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseMessage { get; set; }
    }
}