// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PSI.Domains.Entity
{
    public partial class VW_DASHMASTERBP
    {
        public int DashMaterialBPId { get; set; }
        public string UserId { get; set; }
        public string RecordType { get; set; }
        public string RenewalMark { get; set; }
        public string CompanyCode { get; set; }
        public string CustomerCode { get; set; }
        public DateTime? ModelCreationDate { get; set; }
        public string ModelNo { get; set; }
        public string FinancialYear { get; set; }
        public string ModelType { get; set; }
        public string ReasonName { get; set; }
        public DateTime? SaleStartDate { get; set; }
        public string FactoryCode { get; set; }
        public string SupplierCode { get; set; }
        public string MaterialDescription { get; set; }
        public decimal? MaterialVolume { get; set; }
        public string TermCode { get; set; }
        public string CurrencyCode { get; set; }
        public string Model1StartDate { get; set; }
        public string Model1EndDate { get; set; }
        public decimal? Model1Price { get; set; }
        public string Model2StartDate { get; set; }
        public string Model2EndDate { get; set; }
        public decimal? Model2Price { get; set; }
        public DateTime? ModelDiscontinueDate { get; set; }
        public string PreviousItemCode { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string CustomerName { get; set; }
        public string SupplierName { get; set; }
    }
}